### ISSUE TITLE
Custom Calendar

### ISSUE THREAD

**Issue by luisfuertes** [xgfe/react-native-datepicker#1]
Hi, 

Great calendar picker!! But on iOS the Accept and Cancel option are on Chinese language.

Can you give the option for translate it or take the OS language.

And if you could add option to custom the calendar icon i will love you!

Thanks

**Comment by feyy** [comment]
Thanks for your propose！We have solved these in the latest release [v1.1.0](https://github.com/xgfe/react-native-datepicker/releases/tag/v1.1.0) with [docs](https://github.com/xgfe/react-native-datepicker) and example.
Thanks for your love more!
