### ISSUE TITLE
Return Time as AM or PM Instead of 24:59?

### ISSUE THREAD

**Issue by MattyK14** [xgfe/react-native-datepicker#100]
![screen shot 2017-03-10 at 2 28 23 pm](https://cloud.githubusercontent.com/assets/16196171/23806864/f1da2a64-059d-11e7-9a89-6de46b044c3b.png)

Is it possible to say if we select 8:00pm that it displays 8:00pm as seen in the screenshot rather than 20:00?

**Comment by MattyK14** [comment]
format="h:mm a"

**Comment by UtillYou** [comment]
have you solved this problem?
