### ISSUE TITLE
Use minDate and maxDate to disable hours in "time" mode

### ISSUE THREAD

**Issue by OzoTek** [xgfe/react-native-datepicker#101]
Hello,

I am trying to use the datepicker as a timepicker, and I need to disable hours not in the min/max range.
The `minDate` and `maxDate` could work for my use case but didn't seem to disable for hours, is it not available or I did something wrong?

I'm using it like this to test: 

```
<DatePicker
         mode="time"
         maxDate={moment().add(2, 'hours').toISOString()}
         date={moment().toISOString()}/>
```

Thanks.

**Comment by feyy** [comment]
At first, `minDate` and `maxDate` props only work in ios. Then when you use `time` mode meaning use time formatter defaultly. So you shoud use as below, or change the moment formatter string.
```
<DatePicker
         mode="time"
         maxDate="09:00"/>
```

**Comment by OzoTek** [comment]
It works thanks!

**Comment by Wasseing** [comment]
Is it possible to do it with a date time ? I want to avoid the use of 4 different (start date & time && end date & time) pickers to set time period of time.
