### ISSUE TITLE
Changing Icon

### ISSUE THREAD

**Issue by elhamsarikhani** [xgfe/react-native-datepicker#103]
Can I change the icon of the DatePicker?

**Comment by feyy** [comment]
Of curse, with the `iconSource` property.

**Comment by elhamsarikhani** [comment]
Thanks!

**Comment by AgNm** [comment]
@feyy can you please share example for same.

Also please let me know how can i apply calendar icon like mentioned in below Native base link:

` <Icon name='home' />`

https://docs.nativebase.io/Components.html#icon-def-headref

Thanks in Advance.

**Comment by fvicente** [comment]
@AgNm according to the documentation you provided, Native Base's Icon uses Ionicons from React Native Vector Icons, so maybe this can help.

I'm using [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons), and I was able to use one of the vector icons by converting it first to bitmap, by using its **getImageSource** method, like this:

```javascript
import MaterialIcon from 'react-native-vector-icons/MaterialIcons'

class Main extends Component {

  constructor(props) {
    super(props)
    MaterialIcon.getImageSource('access-time', 20, 'black').then(
      (source) => this.timeIcon = source
    )
    ...
  }

  render() {
            <DatePicker
              date={this.state.time}
              mode="time"
              placeholder="Time"
              confirmBtnText="Confirm"
              cancelBtnText="Cancel"
              iconSource={this.timeIcon}
            />
  }
}
```

**Comment by alawneh0** [comment]
use `iconComponent` property.
like this:
```js
import Icon from 'react-native-vector-icons/MaterialIcons'

class Main extends Component {

  ...
  render() {
            <DatePicker
              date={this.state.startDate}
              mode="datetime"
              placeholder="Start Date"
              iconComponent={
                <Icon 
                size={30}
                color='#333333' 
                name='access-time' 
                /> 
             }
            />
  }
}
```

**Comment by dhcmega** [comment]
Hi, is it possible to locate iconComponent on the left? It's on the right by default. Thanks!

**Comment by Almighty-aravind** [comment]
> Hi, is it possible to locate iconComponent on the left? It's on the right by default. Thanks!

Ya,  Just add custom Property
customStyles={{
                    dateIcon: {
                      position: 'absolute',
                      left: 0,
                      top: 4
                    }
                  }}

**Comment by kiranojhanp** [comment]
> 
> 
> > Hi, is it possible to locate iconComponent on the left? It's on the right by default. Thanks!
> 
> Ya, Just add custom Property
> customStyles={{
> dateIcon: {
> position: 'absolute',
> left: 0,
> top: 4
> }
> }}

hey this isn't working for me! can you help?

![image](https://user-images.githubusercontent.com/54209728/115639365-1a4fdb00-a334-11eb-8d74-0f4c210a0037.png)
