### ISSUE TITLE
Minutes are not being updated

### ISSUE THREAD

**Issue by GregTheGreek** [xgfe/react-native-datepicker#104]
I believe i found a bug, for whatever reason I cannot get the minutes to update.

I can select the minutes, but it won't register the change in the minutes. Even the param in the `onDateChange` `e` returns no change in minutes

I have tested without `prop.minuteInterval` same result...  I can change everything except for the minutes.

```
format: 'MMMM DD YY H:MM a';
....
<DatePicker
       date={this.state.endDate}
       mode="datetime"
       confirmBtnText="Ok"
       cancelBtnText="Cancel"
       format={this.state.format}
       minuteInterval={15}
       showIcon={false}
       onDateChange={(e) => this.setState({ endDate: e })}
/>
```

**Comment by feyy** [comment]
The `MM` is `month`. You should use `mm`.
