### ISSUE TITLE
Initial date

### ISSUE THREAD

**Issue by vomchik** [xgfe/react-native-datepicker#113]
Is it possible to set an initial date for DatePicker and don't show this date in input?

**Comment by feyy** [comment]
Not yet.

**Comment by vvusts** [comment]
There is a workaround for this:
- Set initial max date for picker in state this will be used in maxDate property
- Use 'onOpenModal' to set this state property to null
This will leave input empty and in roll picker you will have your initial date.

Hope this helps

**Comment by girishso** [comment]
Used this workaround.. `endDate` is set to null initially

```
hideText={this.state.endDate == null}
```

**Comment by vomchik** [comment]
@girishso thx
