### ISSUE TITLE
AM/PM not always changing

### ISSUE THREAD

**Issue by aaldrich** [xgfe/react-native-datepicker#116]
We have an intermittent issue where the AM/PM doesn't seem to change when it is quickly changed and confirm is pressed. The onDateChange is not sending across the correct values. I've taken a video of this happening with console logs to show what is being sent. It seems like if I pause for a second then hit confirm, it saves correctly. So it looks like some kind of timing issue.

Here is an example: https://www.screenmailer.com/v/7aNzsLSnLMnYFBw

**Comment by feyy** [comment]
Yes! If you click `Confirm` before the animation finish, you can't get the new Date.

**Comment by DevHisham** [comment]
same issue

**Comment by DevHisham** [comment]
same issue

**Comment by DevHisham** [comment]
same issue
