### ISSUE TITLE
Can I only show DatePicker Icon ？

### ISSUE THREAD

**Issue by simonlify** [xgfe/react-native-datepicker#117]
Hi, Can I only show DatePicker Icon? 
and hide the input box ?

**Comment by cuonghv91** [comment]
I want the vice versa, the showIcon property doesnt seem to work, whats goin on ? pls fix

**Comment by JolieNguyen** [comment]
Yes, you can.
If you just want to display icon:
<DatePicker
                        date={this.state.dateFrom}
                        style={{width:30}}
                        mode="date"
                        format="DD-MM-YYYY"
                        minDate={minDate}
                        maxDate={this.getCurrentDate()}
                        confirmBtnText="Confirm"
                        cancelBtnText="Cancel"
                        customStyles={{
                          dateIcon: {
                            width:30,
                            height:30,
                          },
                          dateInput: {
                            height: 0,
                            width: 0,
                            marginRight: -30
                          }
                        }}
                        onDateChange={(date) => {this.setState({dateFrom: date})}}
                      />

If you just want to display text input
<DatePicker
                        date={this.state.dateTo}
                        mode="date"
                        format="DD-MM-YYYY"
                        minDate={this.state.dateFrom}
                        maxDate={this.getCurrentDate()}
                        confirmBtnText="Confirm"
                        cancelBtnText="Cancel"
                        customStyles={{
                          dateIcon: {
                            width:0,
                            height:0,
                          },
                          dateInput: {
                            height: 30,
                          }
                        }}
                        onDateChange={(date) => {this.setState({dateTo: date})}}
                      />

Hope can help you :)

**Comment by avencat** [comment]
You could achieve this easily with #127

**Comment by simonlify** [comment]
thank you, i got it

**Comment by avencat** [comment]
Any review on this issue? Seems like it doesn't work anymore with RN 0.45. Can anyone confirm that?
