### ISSUE TITLE
没有可以选择的日期啊

### ISSUE THREAD

**Issue by jihadwk** [xgfe/react-native-datepicker#13]
点了之后没有可供选择的日期

![2016-06-27 11 15 55](https://cloud.githubusercontent.com/assets/18099347/16367699/b6924e14-3c58-11e6-99e7-8bafade2e4b8.png)

**Comment by feyy** [comment]
你用的react-native是0.28.x吧，如果是的话，由于0.28.0去掉了DatePickerIOS的固定宽度引起的。先用customStyles覆盖样式。

```
customStyles={{
  datePicker: {
    alignItems: 'stretch'
  }
}}
```
后面应该会发1.3，因为暂时没有找到能兼容过去版本的解决方案。欢迎提PR.

**Comment by jihadwk** [comment]
用的确实是0.28，谢谢大神

**Comment by liuliangsir** [comment]
thx，I met this issue just now
