### ISSUE TITLE
How to hide border line of datePicker?

### ISSUE THREAD

**Issue by holyporing1** [xgfe/react-native-datepicker#131]
I've tried to set BorderWidth but It's still not work.

**Comment by Darot** [comment]
`dateInput: {
                      borderWidth: 0
          }`

try this

**Comment by ckalpit** [comment]
you can use this prop
```
customStyles={{
                            dateInput: {
                                borderLeftWidth: 0,
                                borderRightWidth: 0,
                                borderTopWidth: 0,
                            }
                        }}
```

**Comment by holyporing1** [comment]
Many Thanks :D

**Comment by ThangEthan** [comment]
dateInput: {
                                            borderLeftWidth: 0,
                                            borderRightWidth: 0,
                                            borderTopWidth: 0,
                                            borderBottomWidth: 0,
                                            
                                        }
use this to get rid of all border lines

**Comment by zidniryi** [comment]
its not work for me?. another solutiuon

**Comment by ronakmistry36** [comment]
Apply `{outline: none}` on class `DayPicker-wrapper`. Worked for me.

**Comment by nspbdz** [comment]
how to use in react js sir? i was try and still same
