### ISSUE TITLE
Prop to prevent a default date to be set

### ISSUE THREAD

**Issue by OzoTek** [xgfe/react-native-datepicker#134]
Hello,

I'm using your datepicker in a form, where the user won't necessarily have to enter a date, because sometimes he doesn't know it yet, so it's not a mandatory field.
The thing is, even though the date variable passed is null, a date is displayed. 
Is it possible to add a property to prevent this? 

Thanks.

Alexandre

**Comment by feyy** [comment]
`placeholder=" "`

**Comment by OzoTek** [comment]
Oh, sorry about that, thanks!
