### ISSUE TITLE
Can't hide the textInput with styles in RN 0.45

### ISSUE THREAD

**Issue by avencat** [xgfe/react-native-datepicker#137]
Before I update to react-native 0.45, I could hide the dateText with such style:

```javascript
dateInput: {
  borderWidth: 0,
  borderStyle: null,
  height: 0,
  width: 0,
},
```

but since I updated, this give me that:

<img width="86" alt="capture d ecran 2017-06-07 a 19 23 36" src="https://user-images.githubusercontent.com/10438281/26891898-e5026220-4bb6-11e7-8b8f-c25c97133666.png">

I managed to make a [PR](https://github.com/xgfe/react-native-datepicker/pull/127) that hides the date text with an option but it is not merged yet, can someone please fix the styling issue or merge the #127 PR ?

**Comment by feyy** [comment]
#127
