### ISSUE TITLE
Android里运行直接弹框显示‘已停止运行’

### ISSUE THREAD

**Issue by pimkle** [xgfe/react-native-datepicker#14]
调用的代码如下：
![4](https://cloud.githubusercontent.com/assets/3403548/16517215/eb6bf2c6-3fae-11e6-9633-333d73756d7a.png)

每次点击这个TouchableOpacity后，在android里就提示‘xxx已停止运行’。

下图是监听器监听到的崩溃信息：

![2](https://cloud.githubusercontent.com/assets/3403548/16516927/5e5321da-3fad-11e6-8d1f-9971d30373c7.png)
![3](https://cloud.githubusercontent.com/assets/3403548/16516930/5e7fb8c6-3fad-11e6-80d9-f22d78e3eb2a.png)

**Comment by feyy** [comment]
Datepicker本来是可点的，你最好不要把他嵌套到另一个可点击的元素里面了。同时我试了，我这边没有复现错误，提供一下你的react-native版本看看

**Comment by pimkle** [comment]
好的 谢谢。0.26 还是 0.27的样子。可是不嵌套的话，我是希望用户点击屏幕上的“开始时间”就能选择时间 现有的可选配置好像不够用。

**Comment by pimkle** [comment]
对了 我把datepicker的style设定为 width 0 height 0 overflow hidden了 在ios上 datepicker就不可见了 然而android上 datepicker还是可见的

**Comment by feyy** [comment]
你可以只给开始时间增加点击的

**Comment by pimkle** [comment]
fixed.
