### ISSUE TITLE
i can't change Color of placeholderText

### ISSUE THREAD

**Issue by holyporing1** [xgfe/react-native-datepicker#143]
i want to change text of date from black to white and i tried to set parameter both placeholderText & textColor but still not work.What should i do?
` customStyles={{
                        dateInput: { borderWidth: 0 },
                        placeholderText: {
                            fontSize: 20,
                            color: '#FFF',
                        },
                        textColor: 'FFF',
                        color: '#FFF'
                    }}`

**Comment by cdesch** [comment]
What was the issue?

**Comment by cdesch** [comment]
For me it ended up being the `dateText` needed to be changed:

```
customStyles={{ 
              dateInput: { borderWidth: 0 }, 
              dateText: { color: '#FFF'}, 
              placeholderText: { fontSize: 20, color: '#FFF', }
            }}
```
