### ISSUE TITLE
I set disabled={false} but Datepicker still touchable

### ISSUE THREAD

**Issue by holyporing1** [xgfe/react-native-datepicker#144]
I want to set DatePicker only show date. so i create DatePicker  like this:
<DatePicker
                    style={{ width: 200 }}
                    date={this.state.date}
                    disabled={false}
                    mode="date"
                    placeholder="select date"
                    format="ll"
                    minDate="01-JAN-2015"
                    maxDate="01-OCT-2017"
                    confirmBtnText="Confirm"
                    cancelBtnText="Cancel"
                    showIcon={false}
                    customStyles={{
                        dateInput: {
                            borderWidth: 0,
                        },
                        dateText: {
                            color: theme.colorWhite,
                        },
                        color: '#FFF'
                    }}
                    onDateChange={(date) => {
                        this.setState({ date: date })
                        this.props.date(date)
                    }}
                />
but when i run the app, DatePicker still touchable and change the date what should i do?

**Comment by manjeets12** [comment]
set it to true
