### ISSUE TITLE
Installation break

### ISSUE THREAD

**Issue by hugohow** [xgfe/react-native-datepicker#146]
Hello,

I'm using react-native 0.41.2, and I have this problem, even If I entirely import the component in my src dir :

Does anyone know where the problem is from ?

Thanks

<img width="765" alt="capture d ecran 2017-07-07 a 14 43 13" src="https://user-images.githubusercontent.com/16501509/27958728-b7e67f26-6324-11e7-9a34-238efbdb8d56.png">

**Comment by hugohow** [comment]
Ok I delete Prop-types options, and it works

**Comment by SouroucheHF** [comment]
@hugohow : Can you explain your solution a little more please because i'm facing the same issue. Thanks !
