### ISSUE TITLE
Change display of calendar ?

### ISSUE THREAD

**Issue by hle50** [xgfe/react-native-datepicker#150]
Can we change the display to dd/mm/yyyy ?
![image](https://user-images.githubusercontent.com/15127659/28447260-e5be6ec4-6df9-11e7-8a8e-3f9a12d80e01.png)

**Comment by micaelomota** [comment]
I'm on the same problem... I tried to change the 'format' atribute but doesn't work

**Comment by arled** [comment]
Has anyone managed to fix this? I'm having the same issue.

**Comment by feyy** [comment]
Use iOS native datepicker component. And the UI is depended by your `Language & Region` setting of the phone.
