### ISSUE TITLE
How do I call the onPressDate instance method?

### ISSUE THREAD

**Issue by paloman** [xgfe/react-native-datepicker#151]

**Comment by wmonecke** [comment]
I am also having trouble with this? How do I manually open the picker modal?
I tried DatePicker.onPressDate()

**Comment by gourav-singhal** [comment]
+1

**Comment by gourav-singhal** [comment]
I get this error
![simulator screen shot 01-aug-2017 4 28 32 pm](https://user-images.githubusercontent.com/22169281/28822366-a159c6ee-76d6-11e7-955c-b9a49466a5fe.png)

**Comment by stereodenis** [comment]
@paloman @wmonecke @gourav-singhal 
you need to call it on ref
```
<DatePicker
  ref={(d) => { this.datepicker = d }}
...

and then
this.datepicker.onPressDate()
```
