### ISSUE TITLE
How to modify confirmBtnText color for Android？

### ISSUE THREAD

**Issue by Adar-Li** [xgfe/react-native-datepicker#154]
thanks

**Comment by HasnAr** [comment]
within react-native you could't you have to modify on native code within your project root open
android/app/src/main/res/values/styles.xml and add

<style name="Dialog.Theme" parent="Theme.AppCompat.Light.Dialog">
	    <item name="colorAccent">#cdd500</item>
	    <item name="android:textColorPrimary">#0000FF</item>
 </style>

clean and re-build again, this should do the trick

**Comment by Adar-Li** [comment]
@HasnAr Thank you very much

**Comment by HasnAr** [comment]
@Adar-Li  dose it work, cause in mine project it doesn't
