### ISSUE TITLE
Is a certain icon library needed?

### ISSUE THREAD

**Issue by plflanagan** [xgfe/react-native-datepicker#158]
I'm using ignite, and with npm issues I've been using yarn. So I installed via

```
yarn add react-native-datepicker
```

and got the following error on import:
![simulator screen shot aug 12 2017 8 38 29 am](https://user-images.githubusercontent.com/9424428/29241574-c8bc7932-7f39-11e7-9411-6b4f4f577127.png)

Thoughts on how to resolve?

**Comment by plflanagan** [comment]
I removed the date_icon.png file, and then re-added it and everything worked fine. Strange, but it worked.

**Comment by feyy** [comment]
Restart the RN packager should work.
