### ISSUE TITLE
PropTypes show warning when passing Moment instance for date

### ISSUE THREAD

**Issue by llamaluvr** [xgfe/react-native-datepicker#166]
### Issue

The documentation on the readme says that a Moment instance is an acceptable value for the date prop of DatePicker. It seems to work just fine when you pass a Moment.js instance, except that a PropTypes warning appears: "Failed PropType Invalid prop `date` supplied to `DatePicker.`.

### Expected Behavior

There is no PropTypes warning.

### Code

```javascript

constructor() {
  this.state = {
    date: new Moment(),
  }
}

render() {
  return (
    <DatePicker date={this.state.date} />
  );
}

```

**Comment by colincwilliams** [comment]
+1

**Comment by femiveys** [comment]
Why does the documentation say you can pass a Moment instance if in reality you can't?

**Comment by feyy** [comment]
So sorry. will fix it.
