### ISSUE TITLE
Doesn't work for RN 49

### ISSUE THREAD

**Issue by gavin-gmlab** [xgfe/react-native-datepicker#183]
### Issue
Getting the following error when trying to run my app with RN 49
TransformError: /Users/.../node_modules/react-native-datepicker/node_modules/moment/moment.js: require() must have a single string literal argument

RN DatePicker version 1.6.0

### Expected Behavior
Should not have this error. Noted that some latest commits have upgraded RN to 49 already, but when can we expect a release?

### Environment

1. `react-native -v`: 0.49.3
2. `node -v`: 7.9.0
3. `npm -v`: 4.2.0
4. `yarn --version`:
5. `target platform`: Both
6. `operating system`: Mac OS 10

**Comment by iamrommel** [comment]
I think upgrading to moment 1.19.1 should solve the issue. I got some info from there 
https://github.com/facebook/metro-bundler/issues/65#issuecomment-336838866

But haven't tried it personally

**Comment by gavin-gmlab** [comment]
Upgrading to moment 1.19.1 resolves the issue
