### ISSUE TITLE
Open modal on custom button press / Custom style for the modal

### ISSUE THREAD

**Issue by cristianonescu** [xgfe/react-native-datepicker#188]
1. I want to press on a button and open just the modal.
Is there a way of doing this?

UPDATE:
I managed to do a trick for the first part:
I wrapped the DatePicker and content I wanted to click on into a `<View/>`
and hid the text and icon. Set the datepicker position to absolute. When the user pressed on the view, the datepicker will be pressed.

```
<View
    style={width: 200, height: 100}>
    <DatePicker
        style={{position: 'absolute', width: 200, height: 100}}
        hideText={true}
        showIcon={false}
        ...
        />
        <MyCustomView/>
</View>
```

2. Also is there a way to style the modal? I want it to cover the whole screen and move the Cancel and Confirm buttons below the picker (now are positioned at the TOP)

**Comment by 404sand808s** [comment]
Did you ever figure out how to style the modal?

**Comment by cristianonescu** [comment]
@404sand808s yeah, I ended up stepping into the module and customise it. There's no other way to do this.
You edit the lib, paste the source somewhere else outside the node_modules, and reference it from your code.

**Comment by 404sand808s** [comment]
Ah ok, too intimidating for my tastes 👍 but thanks!
