### ISSUE TITLE
Option for border box and icon position

### ISSUE THREAD

**Issue by luisfuertes** [xgfe/react-native-datepicker#2]
Hi,

Could you add the option for put icon on left of date box. And for delete border or change style of date box?

PD: On iOS the DatePicker dont adjust to screen size. 
You can put the property width for send Dimensions.width 

Thanks!

**Comment by feyy** [comment]
You can use `customStyles` to change the UI.

**Comment by luisfuertes** [comment]
Can you show me a example plz?

**Comment by feyy** [comment]
```
// customStyles={customStyles}, used with customStyles property
const customStyles = StyleSheet.create({
  dateIcon: {
    position: 'absolute',
    left: 0,
    top: 4,
    marginLeft: 0
  },
  dateInput: {
    marginLeft: 36
  }
});
```

**Comment by luisfuertes** [comment]
Thanks feyy
