### ISSUE TITLE
dateText align to left

### ISSUE THREAD

**Issue by jeypc** [xgfe/react-native-datepicker#220]
How to change dateText position to left ?
I tried using textAlign: 'left' but it is not working

```javascript
customStyles={{
  dateInput: {
    borderWidth: 0
  },
  dateText:{
    textAlign: 'left',
    fontSize: 18,
    color: '#000'
  }
}}
```

**Comment by BlankYum** [comment]
dateInput: {
    borderWidth: 0,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    paddingTop: 6,
  }

**Comment by w-wonk** [comment]
@jeypc try `flex-start` instead of `left`
```
dateInput: {
    padding: 5,
    alignItems: 'flex-start'
}
```

**Comment by jeypc** [comment]
thank you, it solved by using `flex-start`

**Comment by rahulbhankar786** [comment]
just simply do this

 customStyles={{
                            dateInput: {
                              borderWidth: 0
                            },
                            dateInput:{
                                padding: 5,
                                alignItems: 'flex-start'
                            }
                        }}
