### ISSUE TITLE
minDate/maxDate doesn't work for time in datetime mode

### ISSUE THREAD

**Issue by polkolins** [xgfe/react-native-datepicker#223]
### Issue
**minDate**/**maxDate** doesn't work for time in **datetime** mode on android (don't know about iOS). 

### Expected Behavior
**minDate**/**maxDate** works both for **date** and **time** in **datetime** mode

### Code

```javascript

<DatePicker
      style={{width: '100%', paddingTop: 0}}
      date={props.date}
      placeholder={props.placeholder}
      mode="datetime"
      minDate={props.min}
      maxDate={props.max}
      androidMode="spinner"
      is24Hour={true}
      format="YYYY-MM-DD HH:mm"
      confirmBtnText="Confirm"
      iconComponent={<Icon name="perm-contact-calendar" size={20} color="#fff"/>}
      cancelBtnText="Cancel"
      onDateChange={props.handleChange}
    />

```

props which I send as min/max Date looks like this

```javascript

2018-03-08 10:07
```

After setting the minimum date as '2018-03-08 10:07' I still can choose earlier time than min Date

![wloaw6yx7xs](https://user-images.githubusercontent.com/17617903/37143720-45d5a760-22bc-11e8-9e4b-738262a250f4.jpg)

Am I doing something wrong or should I use only Moment.js for setting minDate/maxDate?

### Environment

1. `react-native-cli: 2.0.1`, `react-native: 0.52.0`;
2. `node 9.5.0`;
3. `npm 5.7.1`;
4. `yarn 1.3.2`;
5. `Android`;
6. `Win 10 64x`;

**Comment by Ramaraju1992** [comment]
Same issue here for android only... have you managed that @polkolins...?

**Comment by polkolins** [comment]
@Ramaraju1992 Looks like this issue is not about **react-native-datepicker** component, because it uses android native component **AndroidTimePicker** which doesn't support min/max properties.

source - http://facebook.github.io/react-native/docs/timepickerandroid.html

**Comment by densk1** [comment]
I had an issue with this on IOS using `datetime` mode. Having the `minDate` value follow the same format as the `format` prop did the trick.

**Comment by 94angu** [comment]
According to the documentation, for the react-native-datepicker, minDate is not supported for the Android. It works fine for ios.

I followed the method below to overcome the issue in android.
Source - https://stackoverflow.com/a/58400641/9366229
