### ISSUE TITLE
Ignoring change in props (format / duration / etc.)

### ISSUE THREAD

**Issue by kfiroo** [xgfe/react-native-datepicker#23]
@xgfe Hey,
First of all thanks for writing this cool Date Picker :)

Looks like in the constructor you assign some props to instance variables that you later use in your code, that causes changes in these props to be ignored by code that runs after the change.

Any chance you could fix that?

Thanks,
kfir

**Comment by kfiroo** [comment]
@xgfe Looks like you use it for setting default values to props, you should probably use `getDefaultProps` or ES6 variation `defaultProps`

https://facebook.github.io/react/docs/reusable-components.html#default-prop-values
https://facebook.github.io/react/docs/reusable-components.html#es6-classes
http://www.newmediacampaigns.com/blog/refactoring-react-components-to-es6-classes

**Comment by feyy** [comment]
Thanks for your propose. It's really a terrible implement. Will fix in the next release.

**Comment by kfiroo** [comment]
@feyy Cool! Let me know if I can help :)
