### ISSUE TITLE
min and max  date is not working 

### ISSUE THREAD

**Issue by yoginair** [xgfe/react-native-datepicker#237]

**Comment by Eth3rnit3** [comment]
Yeah, it's the same for me.

**Comment by amrita019** [comment]
Check the format which you have specified and the format in which you are entering the min date and max date.
`<DatePicker
            format="YYYY-MM-DD"
            minDate="1990-05-01"
            maxDate={today}
            customStyles={{
              dateIcon: {
                position: 'absolute',
                left: 0,
                top: 4,
                marginLeft: 0
              },
              dateInput: {
                marginLeft: 36
              }
            }}
          />`


Works for me.

**Comment by wzup** [comment]
Not working!

```javascript
// None of these work
maxDate = { Date.now() }
maxDate = { new Date() }
```

**Comment by yoginair** [comment]
@amrita019 you are right...I am closing this issue

**Comment by developerashish01** [comment]
this worked for me

minDate={moment('1920-01-01')}
