### ISSUE TITLE
iOS "Invalid Date"

### ISSUE THREAD

**Issue by anton6** [xgfe/react-native-datepicker#26]
Hi

I came across the following issue for react-native-datepicker.

This is how I am using datepicker component:
```
<DatePicker
  mode='date'
  placeholder='DD-MM-YYYY'
  format='DD-MM-YYYY'
  date={this.state.dob}
  maxDate={moment()}
  showIcon={false}
  confirmBtnText='Confirm'
  cancelBtnText='Cancel'
  onDateChange={(dob) => { this.setState({dob}) }}
/>
```

Initially this.state.dob is an empty string "" so that placeholder is displayed to the user.

So when I click on datepicker component I have this:
<img width="375" alt="screen shot 2016-07-28 at 17 16 01" src="https://cloud.githubusercontent.com/assets/16119505/17220445/253c7816-54e7-11e6-8f49-2856b892a2da.png">

I was expecting it to default to the current date/time instead of beginning of time.

And if I click on Confirm without selecting any date I get an error "Invalid date".

On Android I do not remember seeing this behaviour.

This is how I am currently solving the problem, but not sure if this is the best solution:

```
getDate(date = this.props.date) {
  if (date instanceof Date) {
    return date;
  } else {
    return date ? Moment(date, this.format).toDate() : Moment().toDate();
  }
}
```

Any help is appreciated, thanks.

**Comment by MaxiSantos** [comment]
I'm still seeing this bug when I don't select any date on iOS. On Android is a random bug. ANy ideas?

**Comment by MaxiSantos** [comment]
ok, for my problem this was not an issue with the datepicker library but with how I was sending the date to moment. Check this: https://stackoverflow.com/questions/41874676/react-native-code-doesnt-work-without-remote-debugger-enabled

Basically I just need to send moment('my date', 'the format so moment can correclty convert my date')

**Comment by jmknoll** [comment]
Somewhat related to this - it appears that if you have value (non-empty string) for both placeholder and date, it will render correct in the simulator, but give `invalid date` on an actual iOS device. Deleting the placeholder provides a workaround, although it may not be ideal for all use cases.

**Comment by WseanKiu** [comment]
I fixed mine like this.., 
<DatePicker
     ...
    date={this.state.dueDate instanceof Date ? this.state.dueDate : this.state.present_date}
    ... />

dueDate could be a string but has a value of invalid date syntax e.g. "0000-00-00" or ""

hope this helps (:

**Comment by gshoanganh** [comment]
convert string to date, you can fix:

```
import moment from 'moment'
..
<DatePiker 
...
date={moment(yourDate, 'YYYY-MM-DD').toDate()}
... />
```
