### ISSUE TITLE
Cannot change the border color of the datepicker.

### ISSUE THREAD

**Issue by amit2908** [xgfe/react-native-datepicker#267]
Currently, I need the transparent color of the date picker. I am able to change the background color but the border color cannot be customized. Not even it can be made zero. How can we achieve it.

**Comment by drehimself** [comment]
I think the solution you are looking for can be found here: https://github.com/xgfe/react-native-datepicker/issues/9. Works for me!

**Comment by amit2908** [comment]
thanks @drehimself it worked.
