### ISSUE TITLE
Custom Date font ?

### ISSUE THREAD

**Issue by symmetriccurve** [xgfe/react-native-datepicker#27]
Is there  a prop to style the date text like fontsize ?

**Comment by symmetriccurve** [comment]
Thanks for the Component. I did Something like this for custom font:
`<View style={styles.container}>
              <View style={{flexDirection:'row',alignItems:'center',justifyContent:'center',height:50,backgroundColor:'peachpuff'}}>
                  <View style={{flex:1,alignItems:'center',justifyContent:'center',height:50,backgroundColor:'coral'}}>
                      <Text style={{color:'white',fontSize:20,fontFamily:'HelveticaNeue-UltraLight',fontWeight:'300'}}> DAY</Text>
                  </View>
                  <View style={{flex:0,alignItems:'center',justifyContent:'center',backgroundColor:'blue'}}>
                  <DatePicker
                  ref="datepicker"
                  style={{width: 0}}
                  date={this.state.date}
                  mode="date"
                  format="MM-DD-YYYY"
                  //minDate="2016-05-01"
                  //maxDate="2016-06-01"
                  confirmBtnText="Confirm"
                  cancelBtnText="Cancel"
                  onDateChange={(date) => {this.setState({date: date});}}
                  showIcon={false}
                  customStyles={{
                  dateInput: {
                    borderColor:'transparent'
                  }
                }}
                  />
                  </View>
                  <TouchableHighlight style={{flex:3,justifyContent:'center',alignItems:'center',height:50}} underlayColor='peachpuff' onPress={()=>{this.refs.datepicker.onPressDate()}} >
                            <Text style={{color:'black',fontSize:30,fontFamily:'HelveticaNeue-UltraLight',fontWeight:'100'}}>{this.state.date}</Text>
                  </TouchableHighlight>
              </View>
          </View>`

**Comment by feyy** [comment]
You can use `customStyles` property to customize your own UI.
