### ISSUE TITLE
It works well on IOS portrait but crash on  landscape 

### ISSUE THREAD

**Issue by Sophia-Gao** [xgfe/react-native-datepicker#28]
Terminating app due to uncaught exception 'UIApplicationInvalidInterfaceOrientation', reason: 'Supported orientations has no common orientation with the application, and [RCTModalHostViewController shouldAutorotate] is returning YES'

**Comment by joncursi** [comment]
The component seems to force the landscape mode into portrait if you try to invoke the picker from landscape, at least for me.

Any plans to support using the picker while in landscape mode?

**Comment by TheChuckster** [comment]
Also, running into this one.
