### ISSUE TITLE
How does' locale= 'zh-cn' take effect on android devices

### ISSUE THREAD

**Issue by vitozyf** [xgfe/react-native-datepicker#294]
### Issue
I set 'locale=' zh-cn 'but it doesn't work on android devices. Is there any way?

### Code

```javascript
<DatePicker
                style={styles.DatePicker}
                date={this.state.QuotedTimeByStart}
                mode="date"
                placeholder="起始时间"
                format="YYYY-MM-DD"
                locale="zh-cn"
                confirmBtnText="确定"
                cancelBtnText="取消"
                showIcon={false}
                androidMode="spinner"
                onDateChange={(date) => {this.setState({QuotedTimeByStart: date})}}
            />
```

### Environment

1. `react-native -v`: 0.57.2
2. `node -v`: 8.11.1
3. `npm -v`:6.4.1
4. `yarn --version`:1.12.1
5. `target platform`: Android | iOS
6. `operating system`:

**Comment by vitozyf** [comment]
It works well on ios devices, but how does it work on android devices?

**Comment by Ray-56** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by vitozyf** [comment]
Forget to close the issues. Android follows the language.

**Comment by Ray-56** [comment]
@vitozyf How do I code this

**Comment by vitozyf** [comment]
locale="zh-cn" 
When the system language is Chinese, the components are also Chinese
