### ISSUE TITLE
安卓如何使用中文？

### ISSUE THREAD

**Issue by Ray-56** [xgfe/react-native-datepicker#308]
请问在安卓使用 如何中文显示？

**Comment by feeling2295** [comment]
解决了吗？可以显示中文吗

**Comment by hou666** [comment]
> 请问在安卓使用 如何中文显示？

解决了吗？可以显示中文吗

**Comment by Ray-56** [comment]
@feeling2295  把安卓手机环境改成中文语言就好了

**Comment by feeling2295** [comment]
> 请问在安卓使用 如何中文显示？

在iOS里面的月份显示英文，请教如何设置中文？

**Comment by hou666** [comment]
locale={'zh'}

**Comment by kelement** [comment]
you can use props locale like https://reactnative.cn/docs/datepickerios/#locale
