### ISSUE TITLE
How to disable?

### ISSUE THREAD

**Issue by jinghun1999** [xgfe/react-native-datepicker#32]
I want to disable the component, but no attr can set to it? any one who have sulotion?

**Comment by feyy** [comment]
You can use `disabled` property.

```
<Datepicker disabled={true} />
```

It's my fault missing it in the doc

**Comment by santhosh77h** [comment]
@feyy why don't you add it in doc now at least....

**Comment by santhosh77h** [comment]
@feyy is it possible to change the style of the disabled datepicker..It would be helpful

**Comment by cosydney** [comment]
@santhosh77h did you manage to change the style of the disabled datepicker ?

**Comment by cosydney** [comment]
Never mind, just found how

For those reading this: 

```
  <DatePicker
          disabled={this.state.show}
          customStyles={{
            disabled:{
              backgroundColor: 'green',
            },
```
