### ISSUE TITLE
DatepickerIOS onDateChange why use timer ?

### ISSUE THREAD

**Issue by 2528768618** [xgfe/react-native-datepicker#323]
### Issue
1、onDateChange why use timer？
2、DatepickerIOS onDateChange reports the wrong date？ 

### Code

```javascript

```

### Environment

1. `react-native -v`:
2. `node -v`:
3. `npm -v`:
4. `yarn --version`:
5. `target platform`: Android | iOS
6. `operating system`:

**Comment by kelement** [comment]
1. We will use timeObject to replace it.
2. We will fix it next version.
