### ISSUE TITLE
placeholder is broken

### ISSUE THREAD

**Issue by atlanteh** [xgfe/react-native-datepicker#33]
if date is not specified the current date is placed by default instead of the placeholder, so placeholder is useless. We actually need it.

**Comment by carlespuyol** [comment]
+1

**Comment by aharons** [comment]
+1

**Comment by eranrgdc** [comment]
+1

**Comment by feyy** [comment]
I'm sorry I can't reappear your issue. Can you give me more info or some code?

**Comment by atlanteh** [comment]
```jsx
<Datepicker placeholder="Please insert a date" />
```
This shows the current date instead of the placeholder.
This happens due to commit [b08fb7e](https://github.com/xgfe/react-native-datepicker/commit/b08fb7e) which fixes issue #26

**Comment by feyy** [comment]
Your code work well in my example. Whether show the placeholder  only depend on `date` and 'placeholder' properties.

[https://github.com/xgfe/react-native-datepicker/blob/master/index.js#L128-L132](https://github.com/xgfe/react-native-datepicker/blob/master/index.js#L128-L132)

**Comment by atlanteh** [comment]
Ok, so I reinstalled the module, made sure I had latest and suddenly it started to work :)
