### ISSUE TITLE
How to programmatically close android datepicker?

### ISSUE THREAD

**Issue by pavermakov** [xgfe/react-native-datepicker#333]
### Use case
Recently I have created a fingerprint-protected lock screen for my react-native app. Basically, when the user leaves the app and comes back later, this screen pops up. However, yesterday I have discovered that on android, if I open up a date picker, then leave the app and come back again, the date picker is still there:
![Screenshot_20190409-155022 — копия](https://user-images.githubusercontent.com/10779996/55851539-ba79a380-5b61-11e9-8fbd-7d36639cd9b7.png)

### Issue
The datepicker cannot be close programmatically

### Expected Behavior
The datepicker should be close programmatically

### Environment

1. `react-native -v`: 0.58.6
2. `node -v`: 10.13.0
3. `npm -v`: 6.4.1
4. `yarn --version`:
5. `target platform`: Android
6. `operating system`:  MacOS High Sierra 10.13.6

**Comment by kelement** [comment]
You can control it with [appstate](https://facebook.github.io/react-native/docs/appstate).
