### ISSUE TITLE
Graphic Problem

### ISSUE THREAD

**Issue by keyz23** [xgfe/react-native-datepicker#347]
Hi guys, I have a problem to change the graph of this datapicker. Basically I should use it in a form. 
I'm looking to change the graph aspect, expecially I would change the rettangle in a line 

![Schermata 2019-07-03 alle 10 13 45](https://user-images.githubusercontent.com/45792743/60575261-889c6580-9d7b-11e9-9e69-953fff5053de.png)

I would change in a line with the text above.
Thank you.

**Comment by gcoro** [comment]
You can use the `customStyles` prop to overwrite default style:

```
<DatePicker
    // other props
    customStyles={{ 
        dateInput: {
	    borderWidth: 0,
	    borderBottomWidth: 1,
            // etc
        }
    }}
/>
```

**Comment by keyz23** [comment]
Thank you!
