### ISSUE TITLE
README needs component styling information

### ISSUE THREAD

**Issue by brandonfujii** [xgfe/react-native-datepicker#35]
The readme needs a better description as to how to style certain elements like placeholder text and date icons.

**Comment by LitbLeo** [comment]
@brandonfujii I can not run it on my device,Did you run it success?

**Comment by feyy** [comment]
Thanks! But there are so much properties you can customize, I haven't figure out how to explain it clearly.
Any idea? PR is welcomed!

**Comment by aqnaruto** [comment]
contact me , i'll help you to describe how props used.

**Comment by aqnaruto** [comment]
看了您用的是官方的控件 您知道怎么修改 androidtimepicker 那绿绿的背景色么？ @feyy

**Comment by aqnaruto** [comment]
do u know how to change the ugly default android timepick background？
![image](https://cloud.githubusercontent.com/assets/9067159/18778472/0995baea-81a7-11e6-8a22-c2957af78a3e.png)

**Comment by joncursi** [comment]
+1 ~ Would be great if the readme listed all of the available keys to use within `customStyles`, right now I'm guessing at it by looking through GitHub issues.

**Comment by nikolal** [comment]
I agree with this.
Is there a possibility to change default red color for icon?

**Comment by feyy** [comment]
@nikolal You can customize your own icon with `iconSource` property.
