### ISSUE TITLE
i is not work,and do not show any wrong message

### ISSUE THREAD

**Issue by aqnaruto** [xgfe/react-native-datepicker#39]
![image](https://cloud.githubusercontent.com/assets/9067159/18751294/11d5bdae-8111-11e6-8256-d534efe689de.png)
when i click it ,it does not show anything

**Comment by aqnaruto** [comment]
我知道你是怎么用的了，看了一下代码。但是这样不太灵活，有时候需求只是需要弹出一个窗而已 。总之，谢谢你。

**Comment by feyy** [comment]
你可以把datepicker渲染在不可见的地方，点击时候调用datepicker的onPressDate方法，如`this.refs.datapicker.onPressDate()`

**Comment by aqnaruto** [comment]
感谢，您可以把这种方法写出来 写到readme上面去，估计您的star还会暴涨。我找了很多开源控件，您做的这个是最好的控件之一。

**Comment by feyy** [comment]
恩，谢谢了。后面会增加上去的

**Comment by aqnaruto** [comment]
你这个用的是系统的组件，你知道怎么改系统组件的那种绿色的颜色么 ，我想改 @feyy
