### ISSUE TITLE
I got warnning 

### ISSUE THREAD

**Issue by rom529** [xgfe/react-native-datepicker#412]
### Issue

Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. 
Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

### Code

```javascript

```

### Environment

1. `react-native -v`:
2. `node -v`:
3. `npm -v`:
4. `yarn --version`:
5. `target platform`: Android | iOS
6. `operating system`:

**Comment by GabrielDvt** [comment]
I got the same warning

**Comment by rom529** [comment]
I solved that when I used "https://github.com/react-native-community/datetimepicker"
