### ISSUE TITLE
Not working correctly on device iPhone 11 Pro Max iOS 13.4.1 

### ISSUE THREAD

**Issue by andrii-trush** [xgfe/react-native-datepicker#415]
### Issue

If set minDate and maxDate on iPhone 11 Pro Max iOS 13.4.1. Cannot select date less than today and this date are not available in the picker.
it works fine on simulator. 

If i don't pass min and max date, I'm receiving blank picker.

![IMG_75FC457D128F-1](https://user-images.githubusercontent.com/14265776/80092714-f19fd480-856b-11ea-805b-9b620441a898.png)

### Code

```javascript
minDate=new Date('1940-01-01')
maxDate=new Date()
```

### Environment

1. `react-native -v`: 0.59.9
2. `node -v`: 10.15.3
3. `npm -v`: 6.13.7
4. `yarn --version`:
5. `target platform`:  iOS
6. `operating system`: macOS Catalina latest

**Comment by andrii-trush** [comment]
Reason - dark mode #365

**Comment by topcoder1208** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/61309193/106254279-9a7d0d80-6229-11eb-986a-32cc5dbb8e8f.png)


Help me!!!

**Comment by andrii-trush** [comment]
@topcoder1208 set light theme for app
https://stackoverflow.com/questions/56537855/is-it-possible-to-opt-out-of-dark-mode-on-ios-13#answer-56546554
