### ISSUE TITLE
Got weird view on IOS

### ISSUE THREAD

**Issue by dorbenzvi** [xgfe/react-native-datepicker#444]
### Issue
I got this view on IOS while on android its works fine:

![image](https://user-images.githubusercontent.com/55704483/107684973-1ce6e200-6cac-11eb-9b66-33c606db12f6.png)

### Expected Behavior

Expected to get the scroller like this:

![image](https://user-images.githubusercontent.com/55704483/107685123-4f90da80-6cac-11eb-9d38-264513a20192.png)

### Code

```javascript

      <DatePicker
      style={{width: '80%'}}
      date={selectedDate}
      mode="date"
      placeholder="select date"
      format="DD-MM-YYYY"
      minDate="11-2-2021"
      maxDate="1-1-2022"
      confirmBtnText="Confirm"
      cancelBtnText="Cancel"
      customStyles={{
        dateIcon: {
          position: 'absolute',
          left: 0,
          top: 4,
          marginLeft: 0
        },
        dateInput: {
          marginLeft: 36
        }
        // ... You can check the source to find the other keys.
      }}
      onDateChange={(date) => {setDate(date)}}
```

### Environment

1. `react-native -v`:
2. `node -v`:
3. `npm -v`:
4. `yarn --version`:
5. `target platform`: iOS
6. `operating system`: IOS 14.4

**Comment by motrukdmytro-ck** [comment]
Same problem

**Comment by vhuerta** [comment]
look at this https://github.com/xgfe/react-native-datepicker/issues/425#issuecomment-763307785

**Comment by dorbenzvi** [comment]
@vhuerta WORKS!!!
Thanks, I have spent hours on that!
