### ISSUE TITLE
能否加一个 minuteInterval 的支持？

### ISSUE THREAD

**Issue by jlala** [xgfe/react-native-datepicker#46]
您好！
能否加一个 minuteInterval 的支持？

**Comment by feyy** [comment]
好的，但由于都是用的React-Native提供的TimePickerAndroid和DatePickerIOS, 所以minuteInterval也只支持ios

**Comment by MingBillCheng** [comment]
@feyy 这个应该在文档里面加一下，就说Ios上面支持minuteInterval参数，我刚刚还是看了源码才知道的
