### ISSUE TITLE
点击确定按钮没反应

### ISSUE THREAD

**Issue by luwu1991** [xgfe/react-native-datepicker#50]
点击确定按钮不触发onDateChange方法，只是在非常少的情况下才会触发，在iOS真机和模拟器上都这样

**Comment by feyy** [comment]
Thanks for your feedback. Will fix immediately! Refer the discussion https://github.com/xgfe/react-native-datepicker/pull/47 .

**Comment by luwu1991** [comment]
我试了最新的commit,问题还是存在，而且我的手机是6s

**Comment by feyy** [comment]
不好意思，可以先使用1.3.x.

**Comment by luwu1991** [comment]
1.3.2版本是可以使用的，感谢~

**Comment by hibearpanda** [comment]
@luwu1991 我剛剛也發現這個問題－ 在6s跟6s Plus 也按不到Confirm, Cancel。我用的版本是1.3.1

想問問你用1.3.2是否暫時解決了這個問題?

**Comment by luwu1991** [comment]
1.3.2版本是没问题的。最新版本是1.4.3了，不知道是不是解决了这个问题，你可以试下
