### ISSUE TITLE
How to set the datepicker width to the full width of the parent view?

### ISSUE THREAD

**Issue by BTMouseKing** [xgfe/react-native-datepicker#56]
It looks like it works only with specific width value (e.g. 200)

**Comment by hjJunior** [comment]
did you got it? If yep, please help me, how can I make this width 100%

**Comment by martjoao** [comment]
@hjJunior Set width:undefined for the DatePicker style.

**Comment by ever-dev** [comment]
In my case, I wrapped the Datepicker with View

`<View style={styles.dateWrapper}>
      <DatePicker
        style={styles.dateInput}
        customStyles={{
          dateInput:
            styles.input,
        }}
        date={value}
        format="YYYY-MM-DD"
        confirmBtnText="Confirm"
        cancelBtnText="Cancel"
        onDateChange={onChange}
      />
  </View>

const styles = StyleSheet.create({
   dateWrapper: { flexDirection: 'row' },
   dateInput: { flexGrow: 1 },
   input: { flexGrow:1 },
});
`
