### ISSUE TITLE
Element type is invalid

### ISSUE THREAD

**Issue by dilipvinu** [xgfe/react-native-datepicker#57]
I have the following code.

```javascript
class DateTester extends Component {

  render() {
    return (
      <DatePicker
        style={{width: 200}}
        date="2016-05-01"
        mode="date"
        placeholder="select date"
        format="YYYY-MM-DD"
        minDate="2016-05-01"
        maxDate="2016-05-15"
        confirmBtnText="OK"
        cancelBtnText="Cancel"
        onDateChange={(date) => { let dob = date; }}
      />
    );
  }
}
```

I'm getting the following error
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `DateTester`.

Any idea what's missing?

**Comment by feyy** [comment]
I'm sorry that I haven't discovery any problem.

**Comment by dilipvinu** [comment]
I found the problem was the way in which I imported the component. It's all good now.
