### ISSUE TITLE
Can't make datepicker full width of its parent container 

### ISSUE THREAD

**Issue by cupcakehunter** [xgfe/react-native-datepicker#63]
so i have been trying to make datepicker take the full width of its parent but failing so far. tried flex: 1 and alignSelf: stretch but no luck so far. anyone knows if it is possible to do this ?

**Comment by feyy** [comment]
You can use `style` prop to overwrite the style, But you should use `{width: -1}` to cover the default width style, then the flex layout can work.

**Comment by anceque** [comment]
also this works: `style={{width: null}}`
