### ISSUE TITLE
Can't set 24h format

### ISSUE THREAD

**Issue by MaximeBonobots** [xgfe/react-native-datepicker#69]
Hello,

The 24 hours format is set using this [rule](https://github.com/xgfe/react-native-datepicker/blob/master/index.js#L167):
```sh
...
 is24Hour: !this.format.match(/h|a/)
...
```

I don't understand this rule, can someone tell me more about it ?
If I set format to "HH[h]mm[m]", it returns false, but in my case I want it to be true.

Maybe is24Hour should be a option passed with ```props``` directly, with a default to```false``` ?

**Comment by yasinugrl** [comment]
You should use format like that,
format={'HH:mm'}
