### ISSUE TITLE
onCancel prop is missing

### ISSUE THREAD

**Issue by traf** [xgfe/react-native-datepicker#72]
Great library!
The only thing that seems to be missing is an oncancel prop. So if the user either presses cancel or taps out of the view to close the modal, there seems to be no callback for that event.

**Comment by blaues0cke** [comment]
@traf Think you can close this since those callbacks now exist.

**Comment by nahuelhds** [comment]
Hey, the onCloseModal is fired when the user chooses a date or cancels the modal. How can I detect when is actually cancelling the action?
