### ISSUE TITLE
How to open calendar componet by click on a text

### ISSUE THREAD

**Issue by nimamyscreen** [xgfe/react-native-datepicker#73]
```
<Text onPress={_pressHere} >
Select date
</Text>

var _onPress = () => {
        return (
            <MyDatePicker/>
        )
    };
```

**Comment by Tinysymphony** [comment]
You can add ref property to the component. For example, <DatePicker ref="a_name"/> . And invoke the internal methods `onPressDate` & `onPressCancel` to toggle the calendar. For your case, write `this.refs.a_name.onPressDate();` in the `_onPress` function

**Comment by appsthatmatter** [comment]
@Tinysymphony and is there a way to hide the actual input field? I tried height:0 and hidden=true without success...

**Comment by danieltr10** [comment]
@Tinysymphony I'm trying to do the same @appsthatmatter

**Comment by appsthatmatter** [comment]
I've implemented it by myself. Will publish it the next days.

---
sent from my smartphone

On Feb 3, 2017 17:58, "Daniel Rizzuto" <notifications@github.com> wrote:

@Tinysymphony <https://github.com/Tinysymphony> I'm trying to do the same
@appsthatmatter <https://github.com/appsthatmatter>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/xgfe/react-native-datepicker/issues/73#issuecomment-277301694>,
or mute the thread

**Comment by feyy** [comment]
Set `style` property `{width: 0, height: 0}` can work.

**Comment by mistenkt** [comment]
@appsthatmatter any ETA on when you will publish it?

**Comment by appsthatmatter** [comment]
till end of this week

**Comment by nimamyscreen** [comment]
@Tinysymphony can you please explain more about using ref?

**Comment by Tinysymphony** [comment]
@nimamyscreen @appsthatmatter My example was deleted accidentally...sorry
here is the code

```jsx
let customStyles = {
  dateInput: {
    width: 0,
    height: 0,
    borderWidth: 0
  }
};
// in render function
<Text
  style={{margin: 100}}
  onPress={() => {this.refs.datepicker.onPressDate()}}>
  Your Text
</Text>
<DatePicker
  style={{width: 0, height: 0}}
  showIcon={false}
  customStyles={customStyles}
  ref="datepicker"
/>
```

hide icon by `showIcon={false}`, hide datepicker's touchable view by `style={{width: 0, height: 0}}`, hide inputBody view by `customStyles` and use ref as a hook.

@nimamyscreen you can learn more about ref through [this document](http://reactjs.cn/react/docs/more-about-refs.html)

**Comment by nimamyscreen** [comment]
thanks it's working but what if the text would be outside date component. how should access the ref from outside.
```
class myComponent extends Component {
   <Text  onPress={}> press date </text>
}

export default class MyDatePicker extends Component {
render() {
        const data  = this.props.data;
        return (
                    <DatePicker
                        ref={(datePicker) => this.onPressDate()}        
                        mode="date"
                        placeholder="Select date"
                        format="YYYY-MM-DD"
                        minDate="2017-01-01"
                        confirmBtnText="Confirm"
                        cancelBtnText="Cancel"
                        showIcon={false}
                        onDateChange={(date) => this.setDate(date)}
                    />            
        )
    }
}
```

**Comment by Tinysymphony** [comment]
@nimamyscreen save the ref in a temporary variable will work.

``` jsx
// define a variable in outside scope that both components can access
let myDatepicker;

// in text render function
<Text onPress={() => myDatepicker && myDatepicker.onPressDate(); }>Press Date</Text>

// in datepicker render function 
<DatePicker
  ref={(datepicker) => myDatepicker = datepicker;}
/>
```

In `onPress` callback, you'd better test whether `myDatepicker` is defined.

**Comment by appbeijing** [comment]
I think remove the component default style is a better way.we can add style by wrap a view tag.

**Comment by chapeljuice** [comment]
I'm doing something similar (using a different input and icon to open up the datepicker). Thanks so much @Tinysymphony for your help so far ...

... but how would I access the selected date using a different element? I thought adding _onDateChange_ attribute to the DatePicker element, but that didn't seem to work.

**Comment by reedyrm** [comment]
Ran into a similar issue, and wanted to post an updated solution since there is now a hideText option, so no need to modifying customStyles.

This is my solution taking the previous answers and applying it to my specific example.

```
class ListItemTimePickerInput extends PureComponent {

  constructor(props) {
    super(props);
  }

  render() {
    const {label, input, ...inputProps} = this.props;

    return [
      <ListItem
        {...inputProps}
        key={'listitem'}
        title={label}
        onPress={() => this.myDatepicker && this.myDatepicker.onPressDate()}
        onPressRightIcon={() => this.myDatepicker && this.myDatepicker.onPressDate()}
        textInputOnFocus={() => this.myDatepicker && this.myDatepicker.onPressDate()}
        hideChevron={true}
        textInput={true}
        textInputEditable={true}
        textInputValue={input.value}
      />,
      <DatePicker
        key={'datepicker'}
        ref={(datepicker) => this.myDatepicker = datepicker}
        onDateChange={input.onChange}
        style={{width: 0, height: 0}}
        confirmBtnText={'Confirm'}
        cancelBtnText={'Cancel'}
        date={input.value}
        mode='time'
        hideText={true}
        showIcon={false}
        {...inputProps}
      />
    ];
  }
}
```

**Comment by pherm** [comment]
someone can you help me? i need to open a screen page on press of the date picker text options
