### ISSUE TITLE
Is there a way to style the date inputs?

### ISSUE THREAD

**Issue by jabad3** [xgfe/react-native-datepicker#8]
For example, for this object, only the width change works:
{width:180,borderWidth:0,borderRadius:5,borderColor:"red"}

**Comment by feyy** [comment]
OH! The `customStyles` property is indeed for this, which is an object of styles. You can specify the `dateTouchBody`、`dateInput`... through the `customStyles`. You can check it [here](https://github.com/xgfe/react-native-datepicker/commit/cb254e4). It's all my fault for the bad document.

**Comment by jabad3** [comment]
Thanks so much Feyy. I see that you've updated the docs:). I got it working on my machine, but I still had a hard time with the docs for this prop. Maybe consider updating the docs with an example:

prop - customStyles	
type - object
description - The hook to customize the datepicker's style. To customize, pass in an object containing styles for "dateTouchBody" and "dateInput".
example -
```
customStyles = {     {dateInput: {borderColor:"blue", borderWidth:1},
                                dateTouchBody: {borderColor:"red", borderWidth:3} }
                          }
```
