### ISSUE TITLE
How to remove the border?

### ISSUE THREAD

**Issue by lsps9150414** [xgfe/react-native-datepicker#9]
Hi, thanks for the great work!

I am curious about the `customStyles` prop. Is this how I can remove the gray border around the date text as well as the calendar icon? How do I use it?

**Comment by lsps9150414** [comment]
I figured it out by reading the source code :)

**Comment by feyy** [comment]
😄👏

**Comment by Anima-t3d** [comment]
In case anyone else has the same question, without having to go through the [source code](https://github.com/xgfe/react-native-datepicker/blob/3a9df99e0307497f6bf2dc273cb589101694111f/index.js#L268-L283):
```
<DatePicker
    customStyles={{dateInput:{borderWidth: 0}}}
    ...
/>
```

**Comment by orsospatrick** [comment]
backgroundColor: "#B0B0B000",
                borderTopColor: "#B0B0B000",
                borderBottomColor: "#B0B0B000",
                borderTopWidth: 0,
                borderBottomWidth: 0,
